config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :categories, except: [:index]
  resources :tasks, except: [:show]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "tasks#index"
  
  get "/incomplete", to: "tasks#incomplete"
  get "/due", to: "tasks#due"
  get "/overdue", to: "tasks#overdue"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/categories_task.rb
class CategoriesTask < ApplicationRecord
	belongs_to :category
	belongs_to :task
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :categories_tasks
	has_many :tasks, through: :categories_tasks
	belongs_to :user
end

app/models/task.rb
class Task < ApplicationRecord
	has_many :categories_tasks
	has_many :categories, through: :categories_tasks
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :tasks
         has_many :categories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to root_path , notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to root_path, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to root_path, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name, :user_id)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  # GET /tasks or /tasks.json
  def index
    @tasks = Task.select{|t| t.user == current_user}
    complete = (Task.where({is_complete: true}).count).to_f
    all = (Task.all.count).to_f - 1
    @percentage = complete/all*100

  end
  
  def incomplete
    @incomplete_tasks = Task.where({is_complete: false})
  end

  def due
    date = Date.today
    week_later_date = date + 7
    @due_tasks = Task.where({due_date: (date..week_later_date)})
  end

  def overdue
    tasks = Task.select{|t| t.user == current_user}
    date = Date.today
    all_overdue_tasks = Task.where("due_date < ?", date)
    @overdue_tasks = all_overdue_tasks.where({is_complete: false})
  end

  # GET /tasks/1 or /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks or /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to root_path, notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to root_path, notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy

    respond_to do |format|
      format.html { redirect_to request.referer, notice: "Task was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:title, :description, :is_complete, :due_date, :user_id, :category_ids=>[])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <% if category.user == current_user %>
        <%= link_to category do %>
          <%= '<i class="fab fa-slack-hash fa-flip-horizontal"></i>'.html_safe %>
          <%= category.name %>
        <% end %>
  <% else %>
  <% end %>

</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label "Category:",  style: "display: block" %>
    <%= form.text_field :name, {class:"category"} %>
  </div>

  <div>
    <%= form.number_field :user_id, id: :task_user_id, value:current_user.id, type: :hidden %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/_sidemenu_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label "Category:",  style: "display: block" %>
    <%= form.text_field :name, {class:"category"} %>
  </div>

  <div>
    <%= form.number_field :user_id, id: :task_user_id, value:current_user.id, type: :hidden %>
  </div>

  <div>
    <%= form.submit "Add" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<link rel="stylesheet" href="app/assets/stylesheets/edit_profile.css">

<h2 style="font-family: 'DejaVu', monospace;">Edit category</h2>

<%= render "form", category: @category %>

app/views/categories/index.html.erb
<script src="https://kit.fontawesome.com/9c7f3e0783.js" crossorigin="anonymous"></script>

<p style="color: green"><%= notice %></p>

<h1>Categories</h1>

<div id="categories">
  <% @categories.each do |category| %>
    <%= render category %>
  <% end %>
</div>

<%= link_to "New category", new_category_path %>

app/views/categories/new.html.erb
<link rel="stylesheet" href="app/assets/stylesheets/edit_profile.css">

<h2 style="font-family: 'DejaVu', monospace;">Add category</h2>

<%= render "form", category: @category %>

app/views/categories/show.html.erb
<script src="https://kit.fontawesome.com/9c7f3e0783.js" crossorigin="anonymous"></script>
<link rel="stylesheet" href="app/assets/stylesheets/show_category.css">
<div class="show">
  <h2 style="font-family: 'DejaVu', monospace;"><%= render @category%></h2>

  <%= link_to '<i class="fas fa-pencil-alt"></i>'.html_safe, edit_category_path(@category), class:"show-link" %> 

  <%= button_to '<i class="fas fa-trash"></i>'.html_safe, @category, method: :delete, class:"show-button show-link" %>

</div>

<p style="color: green"><%= notice %></p>

<% if @category.tasks.empty? == false %>
  <div class="card-columns", style="display: inline-block; column-count: 5;">
    <%= render @category.tasks %>
  </div>
<% else %>
  <p>Hooray! You're all done!🎉</p>
<% end %>

 

app/views/layouts/_header.html.erb
<script src="https://kit.fontawesome.com/9c7f3e0783.js" crossorigin="anonymous"></script>
<link rel="stylesheet" href="app/assets/stylesheets/header.css">

<nav class="navbar navbar-expand-lg navbar-top sticky-top">
  <div class="container-fluid">
    <%= link_to 't <i class="fas fa-meteor"></i> d o'.html_safe, root_path, class:'navbar-brand'%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      
      <div class="welcome-text">
        <span class="navbar-text">
           Hello, <%= current_user.email %>!
        </span>
      </div>

      <ul class="navbar-nav mr-auto">
          <li class="nav-item top-item">
            <%= link_to 'Task overview', root_path, class:"nav-link top-link" %>
          </li>
          <li class="nav-item top-item">
            <%= link_to 'Add task', new_task_path, class:"nav-link top-link" %>
          </li>
          <li class="nav-item top-item">
            <%= link_to 'Add category', new_category_path, class:"nav-link top-link" %>
          </li>
          <li class="nav-item top-item right1">
          <%= link_to '<i class="fas fa-user-astronaut fa-lg"></i>'.html_safe, edit_user_registration_path, class:"nav-link top-link right" %>
        </li>
        <li class="nav-item top-item right2">
            <%= button_to'<i class="fas fa-sign-out-alt fa-lg"></i>'.html_safe, destroy_user_session_path, class:"nav-link button top-link right", method: :delete %>
        </li>
      </ul> 
    </div>
  </div>
</nav>


app/views/layouts/_sidemenu.html.erb
<script src="https://kit.fontawesome.com/9c7f3e0783.js" crossorigin="anonymous"></script>
<link rel="stylesheet" href="app/assets/stylesheets/sidemenu.css">

<div class="sidebar">
	<div class="usermenu">
		<ul class="menu-list">
			<li class="menu-item">
				<%= render "categories/sidemenu_form", category: Category.new(params.permit(:name, :user_id)) %>
			</li>
			<li class="menu-item">
				<%= link_to '<i class="fas fa-tasks"></i> All tasks'.html_safe, root_path %>
			</li>
			<li class="menu-item">
				<%= link_to '<i class="far fa-clock"></i> Incomplete'.html_safe, "/incomplete" %>
			</li>
			<li class="menu-item">
				<%= link_to '<i class="far fa-calendar"></i> Due soon'.html_safe, "/due" %>
			</li>
			<li class="menu-item">
				<%= link_to '<i class="far fa-calendar-times"></i> Overdue'.html_safe, "/overdue" %>
			</li>
			<li class="menu-item">
				<% Category.all.each do |category| %>
  					<%= render "categories/category", category: category %>
					<% end %>
			</li>
		</ul>
	</div>
</div>				

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- Include Twitter Bootstrap and jQuery: -->
    <link rel="stylesheet" href="css/bootstrap.min.css" type="text/css"/>
    <script type="text/javascript" src="js/jquery.min.js"></script>
    <script type="text/javascript" src="js/bootstrap.min.js"></script>
     
    <!-- Include the plugin's CSS and JS: -->
    <script type="text/javascript" src="js/bootstrap-multiselect.js"></script>
    <link rel="stylesheet" href="css/bootstrap-multiselect.css" type="text/css"/>

    <title>Todo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

  </head>
  <body>
    <% if current_user %>
      <%= render 'layouts/header' %>
      <%= render "layouts/sidemenu" %>
      <div class="container", style="padding-left: 10vw;">
        </br>
        <%= yield %>
      </div>
    <% else %>
      <div class="container background">
        <%= yield %>
      </div>
    <% end %>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task) do |form| %>
  <% if task.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 

  <div class="field">
    <%= form.label :title%>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label "Completed?"%>
    <%= form.check_box :is_complete, value: false %>
  </div>

  <div class="field">
    <%= form.label :due_date, style: "display: block" %>
    <%= form.date_field :due_date %>
  </div>

<% if Category.select{|c| c.user == current_user} != nil %>
  <div class="field">
    <%= form.label :categories, style: "display: block" %>
    <%= form.collection_check_boxes :category_ids, Category.select{|c| c.user == current_user}, :id, :name, {}, {multiple: true } do |b|%>
      <%= b.check_box %>
        <span class="form-check-input" type="checkbox"></span>
      <%= b.text %>
        <span class="form-check-label"></span>
    <% end %>
  </div>
  <% else %>
  <% end %>

  <div>
    <%= form.number_field :user_id, id: :task_user_id, value:current_user.id, type: :hidden %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<script src="https://kit.fontawesome.com/9c7f3e0783.js" crossorigin="anonymous"></script>

<link rel="stylesheet" href="app/assets/stylesheets/task_index.css">
<div id="<%= dom_id task %>">
  <% if task.user == current_user %>
    <div class="card task-card" style=" width: 18.5vw;">
      <div class="card-body">
        <p class="card-title">
            <strong class="title"><%= task.title %></strong>
            <%= link_to '<i class="fas fa-pencil-alt"></i>'.html_safe, edit_task_path(task), style:"font-size: 15px;"%>
        </p>

        <p class="card-text">
          <%= task.description %>
        </p>

        <% if task.due_date != nil %>
          <p>
            <strong>Due date:</strong>
            <%= task.due_date %>
          </p>
        <% else %>
        <% end %>


        <% if task.is_complete == true %>
        <p>
          <strong>Completion status:</strong>
          <i class="fas fa-check", style="color: #03919b;"></i>
        </p>
        <% else %>
          <p>
            <strong>Completion status:</strong>
            <i class="fas fa-times", style="color: #d70f64;"></i>
          </p>
        <% end %>

        <p>
          <%= render task.categories %>
        </p>

        <%= button_to 'Delete task', task, method: :delete, class:"card-button" %>
      </div>
    </div>
  <% else %>
  <% end %>

</div>

app/views/tasks/due.html.erb
<script src="https://kit.fontawesome.com/9c7f3e0783.js" crossorigin="anonymous"></script>


<h2 style="font-family: 'DejaVu', monospace;">Due in 7 days</h2>

<p style="color: #03919b"><%= notice %></p>

<% if @due_tasks != nil %>
  <div class="card-columns", style="display: inline-block; column-count: 5;">
    <% @due_tasks.each do |task| %>
      <tr>
        <%= render task %>      
      </tr>
    <% end %>
  </div>
<% else %>
  <p>Hooray! You're all done!🎉</p>
<% end %>

</table>

app/views/tasks/edit.html.erb
<link rel="stylesheet" href="app/assets/stylesheets/edit_profile.css">
<h2 style="font-family: 'DejaVu', monospace;">Edit task</h2>

<%= render "form", task: @task %>

app/views/tasks/incomplete.html.erb

<script src="https://kit.fontawesome.com/9c7f3e0783.js" crossorigin="anonymous"></script>

<h2 style="font-family: 'DejaVu', monospace;">Incomplete tasks</h2>

<p style="color: #03919b"><%= notice %></p>

<% if @incomplete_tasks != nil %>
  <div class="card-columns", style="display: inline-block; column-count: 5;"> 
      <% @incomplete_tasks.each do |task| %>
        <tr>
          <%= render task %>      
        </tr>
      <% end %>
  </div>
<% else %>
   <p>Hooray! You're all done!🎉</p>
<% end %>
</table>

app/views/tasks/index.html.erb
<script src="https://kit.fontawesome.com/9c7f3e0783.js" crossorigin="anonymous"></script>
<!-- <link rel="stylesheet" href="app/assets/stylesheets/progress.css">
<script src="app/javascript/progress.js"></script> -->

<h2 style="font-family: 'DejaVu', monospace;">Task overview</h2>

<p style="color: #03919b"><%= notice %></p>

<% if @tasks != nil%>
  <div class="card-columns", style="display: inline-block; column-count: 4;">
      <% @tasks.each do |task| %>
        <%= render task %>      
      <% end %>
  </div>
<% else %>
  <p>Hooray! You're all done!🎉</p>
<% end %>

app/views/tasks/new.html.erb
<link rel="stylesheet" href="app/assets/stylesheets/edit_profile.css">
<h2 style="font-family: 'DejaVu', monospace;">Add task</h2>

<%= render "form", task: @task %>

  

app/views/tasks/overdue.html.erb

<script src="https://kit.fontawesome.com/9c7f3e0783.js" crossorigin="anonymous"></script>

<h2 style="font-family: 'DejaVu', monospace;">Overdue</h2>

<p style="color: #03919b"><%= notice %></p>

<% if @overdue_tasks != nil%>
  <div class="card-columns", style="display: inline-block; column-count: 5;">
    <% @overdue_tasks.each do |task| %>
      <tr>
        <%= render task %>      
      </tr>
    <% end %>
  </div>
<% else %>
   <p>Hooray! You're all done!🎉</p>
<% end %>

</table>

app/views/tasks/show.html.erb
<script src="https://kit.fontawesome.com/9c7f3e0783.js" crossorigin="anonymous"></script>

<p style="color: #03919b"><%= notice %></p>

<%= render @task %>

<div>
  <%= link_to "Back to tasks", tasks_path %>
</div>